### ISSUE TITLE
Read+convert functionalities in BUTool and plugins

### ISSUE THREAD

**Issue by alpakpinar** [apollo-lhc/ApolloTool#6]
Read+convert functionalities are being implemented in `BUTool-IPBus-Helpers` repository, as a part of `IPBusIO` class.

The latest development for this feature is under the `feature/smart_pointer` branch located [here](https://github.com/alpakpinar/ApolloTool/tree/feature/smart_pointer).

The development so far:
- Read+convert member functions are implemented as a part of `IPBusIO` class.
- BUTool command line `readconvert` function has been implemented with the new functions.

To do:
- Clean up redundant code in `IPBusRegHelper` and `BUTool::RegisterHelper`

**Comment by dgastler** [comment]
Solved about 6 months ago by Alp.
